In [4]:
import duckdb
import pandas as pd

In [5]:
sql_query = '''
show tables
'''

with duckdb.connect('../NOAA_Data.db') as con:
    display(con.sql(sql_query).df())

                     name
0       bronze_water_data
1        bronze_wind_data
2  gold_marine_conditions
3       silver_water_data
4        silver_wind_data

In [9]:
sql_query = '''
SELECT * FROM bronze_water_data
'''

with duckdb.connect('../NOAA_Data.db') as con:
    display(con.sql(sql_query).df())

                       t      v                  pulled_at
0    2026-07-02 02:48:00  2.890 2026-07-09 02:45:39.831908
1    2026-07-02 02:54:00  2.664 2026-07-09 02:45:39.831908
2    2026-07-02 03:00:00  2.602 2026-07-09 02:45:39.831908
3    2026-07-02 03:06:00  2.365 2026-07-09 02:45:39.831908
4    2026-07-02 03:12:00  2.287 2026-07-09 02:45:39.831908
...                  ...    ...                        ...
1604 2026-07-08 19:12:00  4.869 2026-07-09 02:45:39.831908
1605 2026-07-08 19:18:00  4.800 2026-07-09 02:45:39.831908
1606 2026-07-08 19:24:00  4.580 2026-07-09 02:45:39.831908
1607 2026-07-08 19:30:00  4.705 2026-07-09 02:45:39.831908
1608 2026-07-08 19:36:00  4.491 2026-07-09 02:45:39.831908

[1609 rows x 3 columns]

In [33]:
sql_query = '''
SELECT * FROM gold_marine_conditions
ORDER BY observed_at DESC LIMIT 50 offset 380
'''

with duckdb.connect('../NOAA_Data.db') as con:
    display(con.sql(sql_query).df())

,observed_at,water_level_ft,wind_speed_kts,wind_category,tide_direction
0,2026-07-07 05:36:00,3.068,5.64,breezy,falling
1,2026-07-07 05:30:00,3.035,6.03,breezy,falling
2,2026-07-07 05:24:00,3.173,4.86,calm,falling
3,2026-07-07 05:18:00,3.278,6.22,breezy,falling
4,2026-07-07 05:12:00,3.255,6.22,breezy,falling
5,2026-07-07 05:06:00,3.494,6.03,breezy,falling
6,2026-07-07 05:00:00,3.294,7.19,breezy,falling
7,2026-07-07 04:54:00,3.379,7.39,breezy,falling
8,2026-07-07 04:48:00,3.406,7.78,breezy,falling
9,2026-07-07 04:42:00,3.455,7.19,breezy,falling
10,2026-07-07 04:36:00,3.550,6.61,breezy,falling
11,2026-07-07 04:30:00,3.504,8.16,breezy,steady
12,2026-07-07 04:24:00,3.507,8.55,breezy,steady
13,2026-07-07 04:18:00,3.412,8.36,breezy,steady
14,2026-07-07 04:12:00,3.563,6.80,breezy,steady
15,2026-07-07 04:06:00,3.583,6.41,breezy,steady
16,2026-07-07 04:00:00,3.576,6.41,breezy,steady
17,2026-07-07 03:54:00,3.789,7.39,breezy,steady
18,2026-07-07 03:48:00,3.606,7.39,breezy,steady
19,2026-07-07 03:42:00,3.852,7.39,breezy,rising
20,2026-07-07 03:36:00,3.720,7.39,breezy,rising
21,2026-07-07 03:30:00,3.806,7.78,breezy,rising
22,2026-07-07 03:24:00,3.839,7.58,breezy,rising
23,2026-07-07 03:18:00,3.806,9.14,breezy,rising
24,2026-07-07 03:12:00,3.786,9.33,breezy,rising
25,2026-07-07 03:06:00,3.970,8.36,breezy,rising
26,2026-07-07 03:00:00,3.796,8.36,breezy,rising
27,2026-07-07 02:54:00,3.950,7.78,breezy,rising
28,2026-07-07 02:48:00,3.819,9.72,breezy,rising
29,2026-07-07 02:42:00,3.819,8.94,breezy,rising
30,2026-07-07 02:36:00,3.780,6.61,breezy,rising
31,2026-07-07 02:30:00,3.727,7.19,breezy,rising
32,2026-07-07 02:24:00,3.852,8.55,breezy,rising
33,2026-07-07 02:18:00,3.648,6.41,breezy,rising
34,2026-07-07 02:12:00,3.681,7.78,breezy,rising
35,2026-07-07 02:06:00,3.704,8.55,breezy,rising
36,2026-07-07 02:00:00,3.507,7.78,breezy,rising
37,2026-07-07 01:54:00,3.691,8.16,breezy,rising
38,2026-07-07 01:48:00,3.501,7.78,breezy,rising
39,2026-07-07 01:42:00,3.737,7.58,breezy,rising
40,2026-07-07 01:36:00,3.442,7.58,breezy,rising
41,2026-07-07 01:30:00,3.717,8.94,breezy,rising
42,2026-07-07 01:24:00,3.530,9.91,breezy,rising
43,2026-07-07 01:18:00,3.602,8.55,breezy,rising
44,2026-07-07 01:12:00,3.478,7.78,breezy,rising
45,2026-07-07 01:06:00,3.474,9.14,breezy,rising
46,2026-07-07 01:00:00,3.445,7.58,breezy,rising
47,2026-07-07 00:54:00,3.314,8.94,breezy,rising
48,2026-07-07 00:48:00,3.596,8.55,breezy,rising
49,2026-07-07 00:42:00,3.406,9.72,breezy,rising

In [3]:
sql_query = '''
DROP TABLE IF EXISTS bronze_water_levels



'''
with duckdb.connect('../NOAA_Data.db') as con:
    display(con.sql(sql_query).df())

AttributeError: 'NoneType' object has no attribute 'df'

In [24]:
import duckdb

con = duckdb.connect("../NOAA_Data.db")
con.execute("DROP TABLE IF EXISTS bronze_water_data")
con.close()

print("Table dropped.")

Table dropped.